version: "3.9"

services:
  web:
    build: .
    container_name: linkup-web
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_DB=linkupdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    command: >
      sh -c "python wait_for_db.py && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 a_core.asgi:application"

  redis:
    image: redis:7-alpine
    container_name: linkup-redis
    ports:
      - "6379:6379"
  db:
    image: postgres:15
    container_name: linkup-db
    environment:
      - POSTGRES_DB=linkupdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"